# Gunakan Python versi 3.9
FROM python:3.9

# Buat folder kerja
WORKDIR /code

# Copy requirements dan install library
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copy semua file code kamu ke dalam container
COPY . .

# Beri izin akses ke folder cache (Penting buat Hugging Face)
RUN chmod -R 777 /code

# Jalankan aplikasi (Hugging Face pakai port 7860)
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]